version: '3'

services:
  db:
    image: postgres:10.7-alpine
    restart: unless-stopped
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rtd
      - POSTGRES_PASSWORD=rtd-password
      - POSTGRES_USER=rtd-user
      - POSTGRES_HOST=db
    networks:
      - readthedocs
  redis:
    image: redis:5.0.4-alpine
    restart: unless-stopped
    networks:
      - readthedocs
  elasticsearch:
    image: elasticsearch:6.7.0
    restart: unless-stopped
    volumes:
      - /usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - readthedocs
  web:
    build:
      context: .
    restart: unless-stopped
    volumes: &common-volumes
      - ./.data/rtd/builds:/readthedocs.org/user_builds
      - ./.data/rtd/private_cname_project:/readthedocs.org/private_cname_project
      - ./.data/rtd/private_cname_root:/readthedocs.org/private_cname_root
      - ./.data/rtd/private_web_root:/readthedocs.org/private_web_root
      - ./.data/rtd/public_cname_project:/readthedocs.org/public_cname_project
      - ./.data/rtd/public_cname_root:/readthedocs.org/public_cname_root
      - ./.data/rtd/public_web_root:/readthedocs.org/public_web_root
      - ./.data/rtd/static:/readthedocs.org/static
    environment:
      - RTD_ADMIN_USERNAME=rtd-admin
      - RTD_ADMIN_EMAIL=rtd-admin@example.com
    networks:
      - readthedocs
    depends_on:
      - db
      - redis
      - elasticsearch
  nginx:
    build:
      context: nginx
    restart: unless-stopped
    volumes: *common-volumes
    networks:
      - readthedocs
    ports:
      - 8000:8000
    depends_on:
      - web

networks:
  readthedocs:
