version: '3'

services:
  db:
    image: postgres:10.7-alpine
    restart: unless-stopped
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rtd
      - POSTGRES_PASSWORD=rtd-password
      - POSTGRES_USER=rtd-user
      - POSTGRES_HOST=db
  redis:
    image: redis:5.0.4-alpine
    restart: unless-stopped
  web:
    image: readthedocs
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - RTD_ADMIN_USERNAME=rtd-admin
      - RTD_ADMIN_EMAIL=rtd-admin@example.com
      - RTD_DOMAIN=localhost:8000
    depends_on:
      - db
      - redis
